// Code generated by go2go; DO NOT EDIT.


//line main.go2:1
package main

//line main.go2:1
import "fmt"

//line main.go2:17
func main() {
	fmt.Println(instantiate୦୦Contains୦string([]string{"foo", "bar"}, "bar"))
	fmt.Println(instantiate୦୦Contains୦int([]int{1, 2}, 3))
}
//line main.go2:7
func instantiate୦୦Contains୦string(in []string, elem string,) bool {
	for _, val := range in {
		if val == elem {
			return true
		}
	}
	return false
}
//line main.go2:7
func instantiate୦୦Contains୦int(in []int, elem int,) bool {
	for _, val := range in {
		if val == elem {
			return true
		}
	}
	return false
}

//line main.go2:14
type Importable୦ int

//line main.go2:14
var _ = fmt.Errorf
